"""Initial tables

Revision ID: 06025812e268
Revises: e01477dc61a5
Create Date: 2025-10-27 18:15:23.396691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06025812e268'
down_revision: Union[str, Sequence[str], None] = 'e01477dc61a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coffee_shop', sa.String(), nullable=True),
    sa.Column('employee', sa.String(), nullable=True),
    sa.Column('shift_start', sa.DateTime(), nullable=True),
    sa.Column('shift_end', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_coffee_shop'), 'schedule', ['coffee_shop'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_coffee_shop'), table_name='schedule')
    op.drop_table('schedule')
    # ### end Alembic commands ###
