"""report model

Revision ID: 19fa017da4b5
Revises: 2c944768fa69
Create Date: 2025-11-27 10:27:31.703951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19fa017da4b5'
down_revision: Union[str, Sequence[str], None] = '2c944768fa69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'coffee_shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'coffee_shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
