<<<<<<<< HEAD:backend/alembic/versions/457e151aecd6_initial_migration.py
"""Initial migration

Revision ID: 457e151aecd6
Revises: 
Create Date: 2025-11-18 11:28:02.262564
========
"""is_confirmed

Revision ID: 2c944768fa69
Revises: bbb771f5b818
Create Date: 2025-11-20 11:39:31.169194
>>>>>>>> 3d81777eaa334fda906573f7ee83c50a21827d6a:backend/alembic/versions/2c944768fa69_is_confirmed.py

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:backend/alembic/versions/457e151aecd6_initial_migration.py
revision: str = '457e151aecd6'
down_revision: Union[str, Sequence[str], None] = None
========
revision: str = '2c944768fa69'
down_revision: Union[str, Sequence[str], None] = 'bbb771f5b818'
>>>>>>>> 3d81777eaa334fda906573f7ee83c50a21827d6a:backend/alembic/versions/2c944768fa69_is_confirmed.py
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<<< HEAD:backend/alembic/versions/457e151aecd6_initial_migration.py
    op.alter_column('schedule', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('schedule', 'coffee_shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'coffee_shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
========
    op.add_column('schedule', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
>>>>>>>> 3d81777eaa334fda906573f7ee83c50a21827d6a:backend/alembic/versions/2c944768fa69_is_confirmed.py
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<<< HEAD:backend/alembic/versions/457e151aecd6_initial_migration.py
    op.alter_column('users', 'coffee_shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schedule', 'coffee_shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schedule', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
========
    op.drop_column('schedule', 'is_confirmed')
>>>>>>>> 3d81777eaa334fda906573f7ee83c50a21827d6a:backend/alembic/versions/2c944768fa69_is_confirmed.py
    # ### end Alembic commands ###
