"""is_confirmed

Revision ID: 2c944768fa69
Revises: bbb771f5b818
Create Date: 2025-11-20 11:39:31.169194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c944768fa69'
down_revision: Union[str, Sequence[str], None] = 'bbb771f5b818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('schedule', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'is_confirmed')
    # ### end Alembic commands ###
