"""coffeshops2

Revision ID: 3a88843bc452
Revises: e8580a189768
Create Date: 2025-11-12 10:21:06.916778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a88843bc452'
down_revision: Union[str, Sequence[str], None] = 'e8580a189768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffeeshops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('adress', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('schedule', sa.Column('coffee_shop_id', sa.Integer(), nullable=True))
    op.add_column('schedule', sa.Column('status', sa.String(), nullable=True))
    op.add_column('schedule', sa.Column('schedule_start_time', sa.DateTime(), nullable=True))
    op.add_column('schedule', sa.Column('schedule_end_time', sa.DateTime(), nullable=True))
    op.add_column('schedule', sa.Column('actual_start_time', sa.DateTime(), nullable=True))
    op.add_column('schedule', sa.Column('actual_end_time', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_schedule_coffee_shop'), table_name='schedule')
    op.create_index(op.f('ix_schedule_coffee_shop_id'), 'schedule', ['coffee_shop_id'], unique=False)
    op.create_foreign_key(None, 'schedule', 'coffeeshops', ['coffee_shop_id'], ['id'])
    op.drop_column('schedule', 'shift_end')
    op.drop_column('schedule', 'shift_start')
    op.drop_column('schedule', 'employee')
    op.drop_column('schedule', 'coffee_shop')
    op.add_column('users', sa.Column('coffee_shop_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'users', 'coffeeshops', ['coffee_shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'coffee_shop_id')
    op.add_column('schedule', sa.Column('coffee_shop', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('schedule', sa.Column('employee', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('schedule', sa.Column('shift_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('schedule', sa.Column('shift_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_index(op.f('ix_schedule_coffee_shop_id'), table_name='schedule')
    op.create_index(op.f('ix_schedule_coffee_shop'), 'schedule', ['coffee_shop'], unique=False)
    op.drop_column('schedule', 'actual_end_time')
    op.drop_column('schedule', 'actual_start_time')
    op.drop_column('schedule', 'schedule_end_time')
    op.drop_column('schedule', 'schedule_start_time')
    op.drop_column('schedule', 'status')
    op.drop_column('schedule', 'coffee_shop_id')
    op.drop_table('coffeeshops')
    # ### end Alembic commands ###
