"""user data_work_start

Revision ID: 64582b637e4c
Revises: 6c1e25a7ae69
Create Date: 2025-11-15 11:15:05.943075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64582b637e4c'
down_revision: Union[str, Sequence[str], None] = '6c1e25a7ae69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('data_work_start', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'data_work_start')
    # ### end Alembic commands ###
