"""update schedule

Revision ID: 6c1e25a7ae69
Revises: 3a88843bc452
Create Date: 2025-11-14 09:51:09.957478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c1e25a7ae69'
down_revision: Union[str, Sequence[str], None] = '3a88843bc452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schedule', 'coffee_shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schedule', 'schedule_start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('schedule', 'schedule_end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'schedule_end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('schedule', 'schedule_start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('schedule', 'coffee_shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('schedule', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
