"""init2

Revision ID: 72912e408acd
Revises: c1ca6de85219
Create Date: 2026-01-15 19:50:15.047650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72912e408acd'
down_revision: Union[str, Sequence[str], None] = 'c1ca6de85219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('coffee_shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'coffeeshops', ['coffee_shop_id'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'coffee_shop_id')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
